spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FocusCrew-4/sparta-logistics-config.git

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 19090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:18080/eureka/
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기
  instance:
    hostname: config-server  # 클라이언트 호스트 이름
    prefer-ip-address: true  # IP 주소 사용 선호
    lease-renewal-interval-in-seconds: 30  # 리스 갱신 간격
    lease-expiration-duration-in-seconds: 90  # 리스 만료 기간
