spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:19090"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka/
  instance:
    prefer-ip-address: true
    hostname: product-service
