spring:
  application:
    name: order-service
  profiles:
    active: local
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

    openfeign:
      client:
        config:
          default:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic

          product-service:
            connect-timeout: 2000
            read-timeout: 3000

          hub-service:
            connect-timeout: 2000
            read-timeout: 3000

  datasource:
    url: jdbc:postgresql://postgresql-server:5432/d_order
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  kafka:
    # 도커 컨테이너에서 실행 시 로컬에서 실행 시
    bootstrap-servers: kafka-server:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 5050

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:18080/eureka/  # Eureka 서버 URL
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기
  instance:
    hostname: order-service  # 클라이언트 호스트 이름
    prefer-ip-address: true  # IP 주소 사용 선호
    lease-renewal-interval-in-seconds: 30  # 리스 갱신 간격
    lease-expiration-duration-in-seconds: 90  # 리스 만료 기간


# docker에서 띄우지 않고 사용하기 위한 yml 설정
#spring:
#  application:
#    name: order-service
#  profiles:
#    active: local
#  config:
#    import: "optional:configserver:"
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/default
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#
#  kafka:
#    # 도커 컨테이너에서 실행 시 로컬에서 실행 시
#    bootstrap-servers: localhost:9092
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: order-service
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#
#server:
#  port: 5050
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:18080/eureka/  # Eureka 서버 URL
#    register-with-eureka: true  # Eureka 서버에 등록
#    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기
#  instance:
#    hostname: order-service  # 클라이언트 호스트 이름
#    prefer-ip-address: true  # IP 주소 사용 선호
#    lease-renewal-interval-in-seconds: 30  # 리스 갱신 간격
#    lease-expiration-duration-in-seconds: 90  # 리스 만료 기간