spring:
  application:
    name: member-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true   # config 서버 접근 실패시 즉시 예외 발생
      retry:
        max-attempts: 6
        initial-interval: 2000
        multiplier: 1.5


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:18080/eureka/
  instance:
    hostname: member-service
