spring:
  application:
    name: gateway-server


  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/v*/delivery-persons/**, /v*/deliveries/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v*/orders/**

        - id: vendor-service
          uri: lb://vendor-service
          predicates:
            - Path=/v*/vendors/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v*/products/**

        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/v*/hubs/**, /v*/hub-routes/**

        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/v*/member/**

server:
  port: 17070

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:18080/eureka/
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기
  instance:
    hostname: gateway-server  # 클라이언트 호스트 이름
    prefer-ip-address: true  # IP 주소 사용 선호
    lease-renewal-interval-in-seconds: 30  # 리스 갱신 간격
    lease-expiration-duration-in-seconds: 90  # 리스 만료 기간
