spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/v*/members/**

        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/v*/hubs/**, /v*/inventory/**, /v*/hub-routes/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/v*/delivery-persons/**, /v*/deliveries/**

        - id: vendor-service
          uri: lb://vendor-service
          predicates:
            - Path=/v*/stores/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v*/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v*/orders/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v*/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8080/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true