spring:
  application:
    name: Eureka-server

server:
  port: 18080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:18080/eureka/

  instance:
    hostname: Eureka-server

  server:
    enable-self-preservation: false

